/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpage;

import Utils.DataValidator;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NewPhongKTX;
import model.SinhVien;
import model.SinhVienDAO;
import model.SinhVienDAO;
import model.PhongktxDAO;

/**
 *
 * @author huong
 */
public class NewPhongKTXPage extends javax.swing.JFrame {

    private DefaultTableModel model;
    private SinhVienDAO svdao;
    private NewPhongKTXPage p;
    int soSV;
    String tinhTrang;
    /**
     * Creates new form NewPhongKTXPage
     */
    public String layMaPhong() {
        String maPhong = txtMAPhong.getText();
        return maPhong;
    }
    
    public int laySoSVHT() {
         return soSV;
    }
    
    public String layTinhTrang() {
        return tinhTrang;
    }

//    public void laySoSVHT(){
//        int soSV = txtMAPhong
//    }
    public NewPhongKTXPage() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) dssvTable.getModel();
        model.setColumnIdentifiers(new String[]{"Mã sinh viên", "Họ tên", "Mã phòng", "Quê quán", "Sdt", "Giới tính", "ngày đk", "ngày hét hạn"});

        reload();
    }

    protected void reload() {
        try {
            SinhVienDAO dao = new SinhVienDAO();
            List<SinhVien> list = dao.docFile(); // Đọc danh sách sinh viên từ file
            //List<SinhVien> listSVMasv = new ArrayList<>();
            model.setRowCount(0);

            for (SinhVien sv : list) {
                if (sv.getMaPhong().equalsIgnoreCase(txtMAPhong.getText())) {
                    model.addRow(new Object[]{
                        sv.getMasv(), sv.getHoTen(), sv.getMaPhong(), sv.getQueQuan(), sv.getSdt(), sv.getGioiTinh(), sv.getNgayDangKy(), sv.getNgayHetHan()
                    });
                }
            }

            NewPhongKTX p2 = new NewPhongKTX();
            //String maPhong = txtMAPhong;
            p2.capNhatSoLuongSV(txtMAPhong.getText());

            NewPhongKTX p = new NewPhongKTX();
            List<NewPhongKTX> listPhongKTX = p.docPhongKTXFile("PhongKTX.txt");
            for (NewPhongKTX p1 : listPhongKTX) {
                //JOptionPane.showMessageDialog(rootPane, "hãy chọn dòng có sv muốn xóa");

                if (p1.getMaPhong().equalsIgnoreCase(txtMAPhong.getText())) {
                    lbMaPhong.setText("Mã phòng: " + p1.getMaPhong());
                    lbLoaiPhong.setText("Loại phòng: " + p1.getLoaiPhong());
                    lbSoSVMax.setText("Số sinh viên tối đa: " + p1.getSoSVToiDa());
                    lbSoSV.setText("Số sinh viên hiện tại: " + p1.getSoSVHienTai());
                    soSV = p1.getSoSVHienTai();
                    lbTinhTrang.setText("Tình trạng: " + p1.getTinhTrang());
                    tinhTrang = p1.getTinhTrang();
                    //System.out.println("ma phong" + layMaPhong());
                    lbGiaPhong.setText("Giá phòng/người: " + p1.getGiaPhong());
                    break;
                } else {
                    lbMaPhong.setText("Mã Phòng: ");
                    lbLoaiPhong.setText("Loại phòng: " );
                    lbSoSVMax.setText("Số sinh viên tối đa: " );
                    lbSoSV.setText("Số sinh viên hiện tại: " );
                    lbTinhTrang.setText("Tình trạng: " );
                    lbGiaPhong.setText("Giá phòng/người: " );

                }

            }
//            lbMaPhong.setText("Loại Phòng: " + p.());
//            jLabel6.setText("Số sinh viên hiện tại: " + phongKTX.getSoSVHienTai());
//            lbTinhTrang.setText("Số sinh viên tối đa: " + phongKTX.getSoSVToiDa());
//            jLabel7.setText("Tình trạng: " + phongKTX.getTinhTrang());
//            //return count;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btQuayLai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbMaPhong = new javax.swing.JLabel();
        lbLoaiPhong = new javax.swing.JLabel();
        lbTinhTrang = new javax.swing.JLabel();
        lbSoSV = new javax.swing.JLabel();
        lbSoSVMax = new javax.swing.JLabel();
        lbGiaPhong = new javax.swing.JLabel();
        btXoa = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        btThemSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dssvTable = new javax.swing.JTable();
        btSuaPhong = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btTim = new javax.swing.JButton();
        txtMAPhong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 230, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Phòng KTX");

        btQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btQuayLai.setText("Quay lại");
        btQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btQuayLai)
                .addGap(175, 175, 175)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btQuayLai))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 709, -1));

        jPanel2.setBackground(new java.awt.Color(242, 250, 255));

        lbMaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMaPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbLoaiPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTinhTrang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbSoSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSoSV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbSoSVMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSoSVMax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbGiaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbGiaPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCapNhat.setText("Cập nhật trang");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        btThemSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btThemSV.setText("Thêm sinh viên");
        btThemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemSVActionPerformed(evt);
            }
        });

        dssvTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dssvTable);

        btSuaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btSuaPhong.setText("Sửa thông tin phòng");
        btSuaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbSoSV, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(lbSoSVMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGiaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btThemSV)
                        .addGap(51, 51, 51)
                        .addComponent(btCapNhat)
                        .addGap(46, 46, 46)
                        .addComponent(btXoa)
                        .addGap(43, 43, 43)
                        .addComponent(btSuaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbSoSV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbSoSVMax, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btThemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSuaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 710, 410));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTim.setText("Tìm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        txtMAPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btTim)
                .addGap(46, 46, 46)
                .addComponent(txtMAPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btTim)
                    .addComponent(txtMAPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 720, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemSVActionPerformed
        // TODO add your handling code here:
        String maPhong = txtMAPhong.getText(); //************************************************
        //this.setVisible(false);
        ThemSV sv = new ThemSV();
        sv.setText(maPhong);
        sv.setVisible(true);
    }//GEN-LAST:event_btThemSVActionPerformed

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_btTimActionPerformed

    private void btQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayLaiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_btQuayLaiActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        int[] viTriXoa = dssvTable.getSelectedRows();
        SinhVienDAO sv = new SinhVienDAO();
        List<SinhVien> dssv = sv.docFile();
        if (viTriXoa.length == 0) {
            JOptionPane.showMessageDialog(rootPane, "hãy chọn dòng có sv muốn xóa");
        } else {
            int xacNhan = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa không?", "xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (xacNhan == JOptionPane.YES_OPTION) {

                for (int i = viTriXoa.length - 1; i >= 0; i--) {

                    sv.xoaThanhVien(viTriXoa[i], dssv);
                }
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                sv.luuFile(dssv, false); //**********************************
                reload();
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void txtMAPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAPhongActionPerformed

    private void btSuaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaPhongActionPerformed
 

        String maPhong = txtMAPhong.getText(); //************************************************
        //this.setVisible(false);
        SuaTTPhong p = new SuaTTPhong();
        p.setText(maPhong);
        p.setVisible(true);
    }//GEN-LAST:event_btSuaPhongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPhongKTXPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPhongKTXPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPhongKTXPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPhongKTXPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPhongKTXPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btQuayLai;
    private javax.swing.JButton btSuaPhong;
    private javax.swing.JButton btThemSV;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btXoa;
    private javax.swing.JTable dssvTable;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGiaPhong;
    private javax.swing.JLabel lbLoaiPhong;
    private javax.swing.JLabel lbMaPhong;
    private javax.swing.JLabel lbSoSV;
    private javax.swing.JLabel lbSoSVMax;
    private javax.swing.JLabel lbTinhTrang;
    private javax.swing.JTextField txtMAPhong;
    // End of variables declaration//GEN-END:variables
}
