/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notUse;

import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import loginpage.Home;
import loginpage.PhongKTXPage;
import model.PhongKTX;
import model.PhongktxDAO;

/**
 *
 * @author huong
 */
public class KTXPage extends javax.swing.JFrame {
    private List<PhongKTX> dsPhong;
    /**
     * Creates new form KTXPage
     */
    public KTXPage() throws FileNotFoundException {
        dsPhong = PhongktxDAO.getListPhongFromFile();
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt202 = new javax.swing.JButton();
        btP201 = new javax.swing.JButton();
        bt203 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bt101 = new javax.swing.JButton();
        bt102 = new javax.swing.JButton();
        bt103 = new javax.swing.JButton();
        btQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tầng 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        bt202.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt202.setText("Phòng 202");
        bt202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt202ActionPerformed(evt);
            }
        });

        btP201.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btP201.setText("Phòng 201");
        btP201.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btP201MouseClicked(evt);
            }
        });

        bt203.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt203.setText("Phòng 203");
        bt203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt203ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btP201, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(bt202, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(bt203, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btP201, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt202, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt203, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tầng 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        bt101.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt101.setText("Phòng 101");
        bt101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt101ActionPerformed(evt);
            }
        });

        bt102.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt102.setText("Phòng 102");
        bt102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt102ActionPerformed(evt);
            }
        });

        bt103.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt103.setText("Phòng 103");
        bt103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt103ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bt101, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(bt102, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt103, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt101, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt103, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt102, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btQuayLai.setText("Quay lại");
        btQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btQuayLai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btQuayLai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayLaiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_btQuayLaiActionPerformed

    private void btP201MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btP201MouseClicked
        // TODO add your handling code here:
        PhongKTX phong201 = PhongktxDAO.getPhongKTXById(this.dsPhong, "201");
        JFrame newFrame =  new PhongKTXPage(phong201);
        newFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btP201MouseClicked

    private void bt202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt202ActionPerformed
        // TODO add your handling code here:
        PhongKTX phong202 = PhongktxDAO.getPhongKTXById(this.dsPhong, "202");
        JFrame newFrame =  new PhongKTXPage(phong202);
        newFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt202ActionPerformed

    private void bt203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt203ActionPerformed
        // TODO add your handling code here:
        PhongKTX phong203 = PhongktxDAO.getPhongKTXById(this.dsPhong, "203");
        JFrame newFrame =  new PhongKTXPage(phong203);
        newFrame.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_bt203ActionPerformed

    private void bt101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt101ActionPerformed
        // TODO add your handling code here:
        PhongKTX phong101 = PhongktxDAO.getPhongKTXById(this.dsPhong, "101");
        JFrame newFrame =  new PhongKTXPage(phong101);
        newFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt101ActionPerformed

    private void bt102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt102ActionPerformed
        // TODO add your handling code here:
        PhongKTX phong102 = PhongktxDAO.getPhongKTXById(this.dsPhong, "102");
        JFrame newFrame =  new PhongKTXPage(phong102);
        newFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt102ActionPerformed

    private void bt103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt103ActionPerformed
        // TODO add your handling code here:
        PhongKTX phong103 = PhongktxDAO.getPhongKTXById(this.dsPhong, "103");
        JFrame newFrame =  new PhongKTXPage(phong103);
        newFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt103ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KTXPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KTXPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KTXPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KTXPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KTXPage().setVisible(true);
                    //try {
                    //JFrame qlktx =  new KTXPage();
                    //qlktx.setVisible(true);
//                }catch (Exception e) {
//            // Xử lý các ngoại lệ khác nếu có
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(null, "Lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
//        }
// Xử lý ngoại lệ nếu file không được tìm thấy
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(KTXPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KTXPage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt101;
    private javax.swing.JButton bt102;
    private javax.swing.JButton bt103;
    private javax.swing.JButton bt202;
    private javax.swing.JButton bt203;
    private javax.swing.JButton btP201;
    private javax.swing.JButton btQuayLai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
